plants = ['Aloevera','Amla','Amruthaballi','Arali','Arive Dantu','Astma Weed','Badipala','Balloon Vine','Bamboo','Basale','Beans','Betel','Bhrami','Bringaraja','Caricature','Castor','Catharanthus','Chakte','Chilly','Citron Lime (Herelikai)','Coffee',' Rue (Naagdalli)','Coriander','Crape Jasmine','Curry','Doddpathre','Drumstick','Ekka','Eucalyptus','Fenugreek','Ganigale','Ganike','Gasagase','Ginger','Globe Amarnath','Guava','Henna','Hibiscus','Honge','Indian Beech','Indian Mustard','Insulin','Jackfruit','Jamaica Cherry Gasagase','Jamun','Jasmine','Kambajala','Karanda','Kasambruga','Kohlrabi','Lantana','Lemon','Lemongrass','Malabar Nut','Malabar Spinach','Mango','Marigold','Mexican Mint','Mint','Neem','Nelavembu','Nerale','Nooni','Oleander','Onion','Padri','Palak (Spinach)','Papaya','Parijata','Parijatha','Pea','Peepal','Pepper','Pomoegranate','Pumpkin','Raddish','Rasna','Rose','Rose Apple','Roxburgh Fig','Sampige','Sandalwood','Sapota','Seethaashoka','Seethapala','Spinach','Tamarind','Taro','Tecoma','Thumbe','Tomato','Tulsi','Turmeric','Ashoka','Camphor','Kamakasturi','Kepala',]

scientific_names = ['Aloe vera','Phyllanthus emblica','Tinospora cordifolia','Ficus religiosa','Cissampelos pareira','Euphorbia hirta','Andrographis paniculata','Cardiospermum halicacabum','Bambusa vulgaris','Basella alba','Phaseolus vulgaris','Piper betle','Bacopa monnieri','Eclipta prostrata','Carica papaya','Ricinus communis', 'Catharanthus roseus','Sapindus mukorossi','Capsicum annuum','Citrus medica','Coffea arabica','Ruta graveolens','Coriandrum sativum','Nerium oleander','Murraya koenigii','Ruta graveolens','Moringa oleifera','Senna alexandrina','Eucalyptus globulus','Trigonella foenum-graecum', 
'Cinnamomum verum', 
'Moringa oleifera', 
'Ocimum sanctum', 
'Zingiber officinale', 
'Amaranthus cruentus',
'Psidium guajava', 
'Lawsonia inermis', 
'Hibiscus rosa-sinensis', 
'Ailanthus excelsa', 
'Pongamia pinnata', 
'Brassica juncea', 
'Ceropegia febrifuga', 
'Artocarpus heterophyllus', 
'Muntingia calabura', 
'Syzygium cumini', 
'Jasminum sambac', 
'Asparagus racemosus', 
'Carissa carandas', 
'Holoptelea integrifolia', 
'Brassica oleracea', 
'Lantana camara', 
'Citrus limon', 
'Cymbopogon citratus', 
'Justicia adhatoda', 
'Basella alba', 
'Mangifera indica', 
'Tagetes erecta', 
'Mentha piperita', 
'Mentha spicata', 
'Azadirachta indica', 
'Andrographis paniculata', 
'Phyllanthus amarus', 
'Alternanthera sessilis', 
'Nerium oleander', 
'Allium cepa', 
'Cajanus cajan', 
'Spinacia oleracea', 
'Carica papaya', 
'Nyctanthes arbor-tristis', 
'Murraya koenigii', 
'Pisum sativum', 
'Ficus religiosa', 
'Piper nigrum', 
'Punica granatum',
'Cucurbita pepo', 
'Raphanus sativus', 
'Rheum rhabarbarum', 
'Rosa spp.', 
'Syzygium jambos', 
'Ficus benghalensis', 
'Plumeria rubra', 
'Santalum album', 
'Manilkara zapota', 
'Saraca asoca', 
'Averrhoea carambola', 
'Spinacia oleracea', 
'Tamarindus indica', 
'Colocasia esculenta', 
'Tecoma stans', 
'Sphagneticola trilobata', 
'Solanum lycopersicum', 
'Ocimum sanctum', 
'Curcuma longa', 
'Saraca asoca', 
'Cinnamomum camphora', 
'Musk Mallow', 
'Cinnamomum verum'
]

plants_info = [
"Aloevera - A succulent plant with medicinal properties. Used for skincare and wound healing.",
"Amla - A small, sour fruit rich in Vitamin C. Used to boost immunity and hair health.",
"Amruthaballi - A medicinal creeper known as Guduchi. Used to enhance immunity.",
"Arali - Ornamental flowering plant. Used in religious offerings.",
"Arive Dantu - Leafy vegetable rich in nutrients. Used in traditional dishes.",
"Asthma Weed - Medicinal herb. Used in treating respiratory ailments.",
"Badipala - Traditional medicinal plant. Used for wound healing.",
"Balloon Vine - A climbing plant with balloon-like fruits. Used for joint pain relief.",
"Bamboo - Fast-growing grass. Used for construction and furniture.",
"Basale - Leafy vegetable also known as Malabar spinach. Used in cooking for iron content.",
"Beans - Protein-rich legume. Used as a staple food source.",
"Betel - Aromatic leaf. Used in chewing with areca nut and lime.",
"Bhrami - Medicinal herb for brain health. Used in Ayurveda for memory enhancement.",
"Bringaraja - Herbal plant for hair care. Used in hair oil preparation.",
"Caricature - Ornamental plant with distinct leaves. Used in landscaping.",
"Castor - Plant producing oil-rich seeds. Used for castor oil extraction.",
"Catharanthus - Flowering plant with medicinal properties. Used in cancer treatment.",
"Chakte - Medicinal plant. Used for treating skin diseases.",
"Chilly - Spicy fruit of capsicum plant. Used as a spice in cooking.",
"Citron Lime (Herelikai) - Citrus fruit with a sour taste. Used in pickles and juices.",
"Coffee - Plant producing coffee beans. Used for making beverages.",
"Rue (Naagdalli) - Medicinal herb with strong aroma. Used for treating insect bites.",
"Coriander - Aromatic herb. Used as a spice and garnish in cooking.",
"Crape Jasmine - Ornamental flowering plant. Used in religious offerings.",
"Curry - Leafy plant with aromatic leaves. Used in Indian cuisine for flavor.",
"Doddpathre - Medicinal herb. Used to treat colds and coughs.",
"Drumstick - Tree with nutritious pods. Used in cooking and medicine.",
"Ekka - Ornamental plant. Used in traditional medicine.",
"Eucalyptus - Tall tree with aromatic leaves. Used in oils for cold relief.",
"Fenugreek - Herb with edible leaves and seeds. Used in cooking and digestion aid.",
"Ganigale - Medicinal plant. Used for treating skin infections.",
"Ganike - Traditional medicinal plant. Used for fever relief.",
"Gasagase - Poppy seeds plant. Used in traditional sweets and sleep aids.",
"Ginger - Root spice with medicinal properties. Used in digestion and cold relief.",
"Globe Amarnath - Ornamental flowering plant. Used for decorative purposes.",
"Guava - Fruit-bearing tree rich in Vitamin C. Used for immunity boosting.",
"Henna - Plant with natural dyeing properties. Used for coloring hair and skin.",
"Hibiscus - Flowering plant with medicinal uses. Used in hair care and tea.",
"Honge - Tree producing oil-rich seeds. Used for biodiesel production.",
"Indian Beech - Medicinal tree. Used for treating skin diseases.",
"Indian Mustard - Oil-seed plant. Used for mustard oil and cooking.",
"Insulin - Medicinal plant for diabetes control. Used in herbal medicine.",
"Jackfruit - Large tropical fruit. Used as a food source and meat substitute.",
"Jamaica Cherry Gasagase - Fruit-bearing tree. Used for making jams and juices.",
"Jamun - Berry-like fruit. Used in diabetes management.",
"Jasmine - Aromatic flowering plant. Used in perfumes and religious offerings.",
"Kambajala - Medicinal herb. Used for healing wounds.",
"Karanda - Berry-producing shrub. Used for pickles and jams.",
"Kasambruga - Medicinal plant. Used for treating digestive issues.",
"Kohlrabi - Root vegetable. Used in salads and curries.",
"Lantana - Ornamental flowering plant. Used in landscaping.",
"Lemon - Citrus fruit rich in Vitamin C. Used for juices and flavoring.",
"Lemongrass - Aromatic herb. Used in tea and insect repellents.",
"Malabar Nut - Medicinal plant. Used in respiratory treatments.",
"Malabar Spinach - Leafy green vegetable. Used in cooking.",
"Mango - Tropical fruit tree. Used for fresh consumption and pickles.",
"Marigold - Ornamental flowering plant. Used in decorations and religious ceremonies.",
"Mexican Mint - Aromatic herb. Used in treating cough and colds.",
"Mint - Refreshing herb. Used in beverages and digestion aid.",
"Neem - Medicinal tree. Used for skincare and dental care.",
"Nelavembu - Bitter medicinal plant. Used in fever treatment.",
"Nerale - Fruit-bearing tree. Used in traditional medicine.",
"Nooni - Medicinal plant. Used in treating infections and boosting immunity.",
"Oleander - Ornamental flowering shrub. Used in landscaping.",
"Onion - Bulb vegetable with strong flavor. Used in cooking.",
"Padri - Medicinal plant. Used in traditional remedies.",
"Palak (Spinach) - Nutrient-rich leafy green. Used in cooking.",
"Papaya - Tropical fruit. Used for digestion and skincare.",
"Parijata - Sacred flowering plant. Used in religious ceremonies.",
"Parijatha - Flowering plant with medicinal properties. Used in Ayurveda.",
"Pea - Edible legume. Used in soups and curries.",
"Peepal - Sacred tree in Hinduism. Used in traditional medicine.",
"Pepper - Spice-producing vine. Used for seasoning and medicine.",
"Pomegranate - Fruit with antioxidant properties. Used for juicing and health benefits.",
"Pumpkin - Large vegetable rich in fiber. Used in soups and sweets.",
"Raddish - Root vegetable with pungent taste. Used in salads and pickles.",
"Rasna - Medicinal herb. Used for treating arthritis and joint pain.",
"Rose - Fragrant flowering plant. Used for perfumes and beauty products.",
"Rose Apple - Tropical fruit tree. Used for fresh consumption.",
"Roxburgh Fig - Tree with edible figs. Used in traditional medicine.",
"Sampige - Fragrant flowering tree. Used for temple offerings.",
"Sandalwood - Aromatic tree. Used in perfumes and religious rituals.",
"Sapota - Sweet tropical fruit. Used in juices and desserts.",
"Seethaashoka - Sacred tree. Used in Ayurveda for women’s health.",
"Seethapala - Fruit-bearing tree. Used for nutrition and medicine.",
"Spinach - Leafy green vegetable. Used for iron-rich meals.",
"Tamarind - Sour fruit. Used in cooking and sauces.",
"Taro - Root vegetable. Used in cooking and traditional dishes.",
"Tecoma - Flowering shrub. Used in landscaping.",
"Thumbe - Medicinal herb. Used in treating colds and fever.",
"Tomato - Red fruit used as a vegetable. Used in cooking and salads.",
"Tulsi - Sacred medicinal herb. Used in herbal teas and immunity boosting.",
"Turmeric - Root spice with anti-inflammatory properties. Used in cooking and medicine.",
"Ashoka - Sacred tree in Hinduism. Used in Ayurveda for women’s health.",
"Camphor - Aromatic plant. Used in religious rituals and medicinal applications.",
"Kamakasturi - Medicinal herb. Used for hair growth and skincare.",
"Kepala - Traditional plant. Used in folk medicine."
]

link = ['https://www.google.com/search?q=Aloevera+plant+details', 'https://www.google.com/search?q=Amla+plant+details', 'https://www.google.com/search?q=Amruthaballi+plant+details', 'https://www.google.com/search?q=Arali+plant+details', 'https://www.google.com/search?q=Arive Dantu+plant+details', 'https://www.google.com/search?q=Astma Weed+plant+details', 'https://www.google.com/search?q=Badipala+plant+details', 'https://www.google.com/search?q=Balloon Vine+plant+details', 'https://www.google.com/search?q=Bamboo+plant+details', 'https://www.google.com/search?q=Basale+plant+details', 'https://www.google.com/search?q=Beans+plant+details', 'https://www.google.com/search?q=Betel+plant+details', 'https://www.google.com/search?q=Bhrami+plant+details', 'https://www.google.com/search?q=Bringaraja+plant+details', 'https://www.google.com/search?q=Caricature+plant+details', 'https://www.google.com/search?q=Castor+plant+details', 'https://www.google.com/search?q=Catharanthus+plant+details', 'https://www.google.com/search?q=Chakte+plant+details', 'https://www.google.com/search?q=Chilly+plant+details', 'https://www.google.com/search?q=Citron Lime (Herelikai)+plant+details', 'https://www.google.com/search?q=Coffee+plant+details', 'https://www.google.com/search?q= Rue (Naagdalli)+plant+details', 'https://www.google.com/search?q=Coriander+plant+details', 'https://www.google.com/search?q=Crape Jasmine+plant+details', 'https://www.google.com/search?q=Curry+plant+details', 'https://www.google.com/search?q=Doddpathre+plant+details', 'https://www.google.com/search?q=Drumstick+plant+details', 'https://www.google.com/search?q=Ekka+plant+details', 'https://www.google.com/search?q=Eucalyptus+plant+details', 'https://www.google.com/search?q=Fenugreek+plant+details', 'https://www.google.com/search?q=Ganigale+plant+details', 'https://www.google.com/search?q=Ganike+plant+details', 'https://www.google.com/search?q=Gasagase+plant+details', 'https://www.google.com/search?q=Ginger+plant+details', 'https://www.google.com/search?q=Globe Amarnath+plant+details', 'https://www.google.com/search?q=Guava+plant+details', 'https://www.google.com/search?q=Henna+plant+details', 'https://www.google.com/search?q=Hibiscus+plant+details', 'https://www.google.com/search?q=Honge+plant+details', 'https://www.google.com/search?q=Indian Beech+plant+details', 'https://www.google.com/search?q=Indian Mustard+plant+details', 'https://www.google.com/search?q=Insulin+plant+details', 'https://www.google.com/search?q=Jackfruit+plant+details', 'https://www.google.com/search?q=Jamaica Cherry Gasagase+plant+details', 'https://www.google.com/search?q=Jamun+plant+details', 'https://www.google.com/search?q=Jasmine+plant+details', 'https://www.google.com/search?q=Kambajala+plant+details', 'https://www.google.com/search?q=Karanda+plant+details', 'https://www.google.com/search?q=Kasambruga+plant+details', 'https://www.google.com/search?q=Kohlrabi+plant+details', 'https://www.google.com/search?q=Lantana+plant+details', 'https://www.google.com/search?q=Lemon+plant+details', 'https://www.google.com/search?q=Lemongrass+plant+details', 'https://www.google.com/search?q=Malabar Nut+plant+details', 'https://www.google.com/search?q=Malabar Spinach+plant+details', 'https://www.google.com/search?q=Mango+plant+details', 'https://www.google.com/search?q=Marigold+plant+details', 'https://www.google.com/search?q=Mexican Mint+plant+details', 'https://www.google.com/search?q=Mint+plant+details', 'https://www.google.com/search?q=Neem+plant+details', 'https://www.google.com/search?q=Nelavembu+plant+details', 'https://www.google.com/search?q=Nerale+plant+details', 'https://www.google.com/search?q=Nooni+plant+details', 'https://www.google.com/search?q=Oleander+plant+details', 'https://www.google.com/search?q=Onion+plant+details', 'https://www.google.com/search?q=Padri+plant+details', 'https://www.google.com/search?q=Palak (Spinach)+plant+details', 'https://www.google.com/search?q=Papaya+plant+details', 'https://www.google.com/search?q=Parijata+plant+details', 'https://www.google.com/search?q=Parijatha+plant+details', 'https://www.google.com/search?q=Pea+plant+details', 'https://www.google.com/search?q=Peepal+plant+details', 'https://www.google.com/search?q=Pepper+plant+details', 'https://www.google.com/search?q=Pomoegranate+plant+details', 'https://www.google.com/search?q=Pumpkin+plant+details', 'https://www.google.com/search?q=Raddish+plant+details', 'https://www.google.com/search?q=Rasna+plant+details', 'https://www.google.com/search?q=Rose+plant+details', 'https://www.google.com/search?q=Rose Apple+plant+details', 'https://www.google.com/search?q=Roxburgh Fig+plant+details', 'https://www.google.com/search?q=Sampige+plant+details', 'https://www.google.com/search?q=Sandalwood+plant+details', 'https://www.google.com/search?q=Sapota+plant+details', 'https://www.google.com/search?q=Seethaashoka+plant+details', 'https://www.google.com/search?q=Seethapala+plant+details', 'https://www.google.com/search?q=Spinach+plant+details', 'https://www.google.com/search?q=Tamarind+plant+details', 'https://www.google.com/search?q=Taro+plant+details', 'https://www.google.com/search?q=Tecoma+plant+details', 'https://www.google.com/search?q=Thumbe+plant+details', 'https://www.google.com/search?q=Tomato+plant+details', 'https://www.google.com/search?q=Tulsi+plant+details', 'https://www.google.com/search?q=Turmeric+plant+details', 'https://www.google.com/search?q=Ashoka+plant+details', 'https://www.google.com/search?q=Camphor+plant+details', 'https://www.google.com/search?q=Kamakasturi+plant+details', 'https://www.google.com/search?q=Kepala+plant+details']

 
